import type { WorkflowDefinition } from "./workflowConfig";

export const DEFAULT_OPPORTUNITY_WORKFLOW: WorkflowDefinition = {
  id: "default_opportunity_flow",
  name: "标准商机审批流程",
  target: "opportunity",
  enabled: true,
  isDefault: true,
  version: 2,
  description:
    "用于商机早期阶段审批：线索确认上传需求说明，项目启动分配解决方案负责人，需求分析上传调研文档，最终审批给出通过或驳回结论。",
  applicableOpportunity: "",
  nodes: [
    {
      id: "op_node_1",
      nodeKey: "lead_confirmation",
      name: "线索确认",
      nodeOrder: 1,
      nodeType: "upload",
      fieldKey: "requirementBriefDocName",
      fieldLabel: "客户需求说明",
      actionButtonLabel: "上传需求说明",
      approverRole: "销售负责人",
      description: "上传客户需求说明文档，确认客户背景与初步诉求。",
      canReject: true,
      rejectStrategy: "terminate",
      rejectCommentRequired: false,
      approvers: [
        {
          approverType: "role",
          approverRef: "sales_owner",
          displayName: "销售负责人",
          voteRule: "any",
          sortOrder: 0,
        },
      ],
    },
    {
      id: "op_node_2",
      nodeKey: "sales_leader_approval",
      name: "销售领导审批",
      nodeOrder: 2,
      nodeType: "approval",
      fieldKey: "bizApprovalStatus",
      fieldLabel: "销售领导审批",
      approverRole: "销售领导",
      description: "确认商机是否值得继续投入，决定是否进入下一阶段。",
      canReject: true,
      rejectStrategy: "terminate",
      rejectCommentRequired: false,
      approvers: [
        {
          approverType: "role",
          approverRef: "sales_manager",
          displayName: "销售领导",
          voteRule: "any",
          sortOrder: 0,
        },
      ],
    },
    {
      id: "op_node_3",
      nodeKey: "solution_leader_approval",
      name: "解决方案领导审批",
      nodeOrder: 3,
      nodeType: "approval",
      fieldKey: "techApprovalStatus",
      fieldLabel: "解决方案领导审批",
      approverRole: "解决方案领导",
      description: "确认售前资源投入方向，并给出技术侧审批意见。",
      canReject: true,
      rejectStrategy: "terminate",
      rejectCommentRequired: false,
      approvers: [
        {
          approverType: "role",
          approverRef: "solution_manager",
          displayName: "解决方案领导",
          voteRule: "any",
          sortOrder: 0,
        },
      ],
    },
    {
      id: "op_node_4",
      nodeKey: "assign_solution_owner",
      name: "分配解决方案负责人",
      nodeOrder: 4,
      nodeType: "assignment",
      fieldKey: "solutionOwnerUsername",
      fieldLabel: "解决方案负责人",
      actionButtonLabel: "选择负责人",
      approverRole: "售前经理 / 项目负责人",
      description: "明确后续由谁承接需求分析和方案设计。",
      canReject: false,
      rejectStrategy: "terminate",
      rejectCommentRequired: false,
      approvers: [
        {
          approverType: "role",
          approverRef: "solution_manager",
          displayName: "售前经理",
          voteRule: "any",
          sortOrder: 0,
        },
      ],
    },
    {
      id: "op_node_5",
      nodeKey: "requirement_analysis",
      name: "需求分析",
      nodeOrder: 5,
      nodeType: "upload",
      fieldKey: "researchDocName",
      fieldLabel: "需求调研文档",
      actionButtonLabel: "上传调研文档",
      approverRole: "解决方案负责人",
      description: "完成需求调研并上传调研文档。",
      canReject: true,
      rejectStrategy: "terminate",
      rejectCommentRequired: false,
      approvers: [
        {
          approverType: "field",
          approverRef: "solutionOwnerUsername",
          displayName: "解决方案负责人",
          voteRule: "any",
          sortOrder: 0,
        },
      ],
    },
    {
      id: "op_node_6",
      nodeKey: "final_approval",
      name: "最终审批",
      nodeOrder: 6,
      nodeType: "approval",
      fieldKey: "approvalStatus",
      fieldLabel: "最终审批",
      approverRole: "销售总监 / 技术总监",
      description: "基于前序材料给出最终通过或驳回结论。",
      canReject: true,
      rejectStrategy: "terminate",
      rejectCommentRequired: true,
      approvers: [
        {
          approverType: "role",
          approverRef: "sales_director",
          displayName: "销售总监",
          voteRule: "any",
          sortOrder: 0,
        },
        {
          approverType: "role",
          approverRef: "tech_director",
          displayName: "技术总监",
          voteRule: "any",
          sortOrder: 1,
        },
      ],
    },
  ],
};

export const DEFAULT_SOLUTION_WORKFLOW: WorkflowDefinition = {
  id: "default_solution_flow",
  name: "标准解决方案审批流程",
  target: "solution",
  enabled: true,
  isDefault: true,
  version: 2,
  applicableOpportunity: "",
  nodes: [
    {
      id: "sol_node_1",
      nodeKey: "tech_review",
      name: "技术评审",
      nodeOrder: 1,
      approverRole: "技术评审专家 / 架构师",
      description: "评估方案技术可行性、风险与资源匹配度。",
    },
    {
      id: "sol_node_2",
      nodeKey: "business_review",
      name: "商务评审",
      nodeOrder: 2,
      approverRole: "商务经理",
      description: "校验报价策略、交付范围与商务条款。",
    },
    {
      id: "sol_node_3",
      nodeKey: "final_solution_approval",
      name: "最终审批",
      nodeOrder: 3,
      approverRole: "业务负责人 / 总监",
      description: "综合技术与商务意见给出最终审批结论。",
    },
  ],
};

export const DEFAULT_WORKFLOWS: WorkflowDefinition[] = [
  DEFAULT_OPPORTUNITY_WORKFLOW,
  DEFAULT_SOLUTION_WORKFLOW,
];
